on:
  repository_dispatch:
    types: [release-published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: linux-releaes
        run: |
          echo "Linux Release call ${{github.ref_name}}"
          git describe --tags
