on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: linux-releaes
        run: |
          echo "Linux Release call ${{github.ref_name}}"
          git describe
