on:
  repository_dispatch:
    types: [release-published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - id: macos-releaes
        run: |
          echo "macOS Release call ${{github.ref_name}}"
          git describe --tags
