on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: Get tags
        run: git fetch --tags --force origin
      - id: macos-releaes
        run: |
          echo "macOS Release call ${{github.ref_name}}"
          git describe --tags
