name: CI - Annotate Tags

on:
  release:
    types: [published]

jobs:
  annotate-tag:
    name: "Annotate tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Configure git"
        run: |
          git config user.email "workflow@febio.org"
          git config user.name "FEBIo Workflow"
      - name: "Annotate tag"
        run: |
          tag=${{ github.ref_name }}
          date="$(git show $tag --format=%aD | head -1)"
          GIT_COMMITTER_DATE="$date" git tag -a -f $tag $tag -m "Annotated ${tag}"
          git push --force origin $tag
          echo $?
          git describe --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dispatch-release-workflow:
    name: "Repository dispatch release workflow"
    runs-on: "ubuntu-latest"
    steps:
      - name: ""
        run: |
           gh api \
             --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/tundranerd/FEBio/dispatches\
            -f "event_type=release-published" -F "client_payload[ref_name]=${{ github.ref_name }}"
