on:
  repository_dispatch:
    types: [release-published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - id: windows-release
        run: |
          echo "Windows Release call ${{github.ref_name}}"
          git describe --tags
