on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: windows-release
        run: |
          echo "Windows Release call ${{github.ref_name}}"
          git describe
